# PART 2

###  :pencil: ***입문 035 :  예외 처리하기***

<br>

자바스크립트 코드를 실행하다 **에러**가 발생하면 그 **즉시 중단**된다. 이를 대비해서 **예외 처리**는 반드시 필요하다. 자바스크립트에서 사용할 수 있는 **예외 처리 방법**에는 **throw 문**과 **try-catch-finally 문**이 있다.

**예외 처리 시** 에러 종류는 크게 **두 가지**로 나뉜다. 

1. 예상치 못한 에러

2. 개발자가 의도한 에러

   여기서 개발자가 의도한 에러란, _코드에서 잘못될 가능성을 예상하고 발생시키는 에러를 의미한다._

먼저, 후자인 경우 **throw 문**을 사용한다.

*throw* 문은 고의로 에러를 발생시켜 예외 상황을 알리는 역할을 한다. 그리고 *thrwo* 문이 실행되면 실행되고 있던 블록을 빠져나간다.

```javascript
// 1.
function checkNumber(val){
    // 1-1.
    if(typeof val !== 'number') throw '유효하지 않은 값입니다.';
    // 1-2.
    console.log('숫자형 값으로 확인되었습니다.');
}
// 2.
checkNumber(100);
// 2-1.
checkNumber('Wrong type');
// 2-2.
console.log('완료');
```

- `1.` 숫자형 값 여부를 확인하는 함수를 선언한다.

- `1-1.` *typeof val*을 통해 숫자형 값이 아닌 경우, *throw*문을 통해 함수 블록을 빠져나간다.
- `1-2.` 숫자형이 확인되면 출력되는 문장이다.
- `2.` 숫자형 값 `100`을 넣으면 3라인이 출력된다.

- `2-1.` 문자형 값 `Wrong type`을 넣으면 *typeof val* 결과값은 *string*을 반환한다. 따라서 2라인 조건문 아래 **trow 문**이 실행된다.
- `2-2.` 7라인에서 에러가 발생하여 예제 코드 실행이 중단된다. 마지막 8라인은 실행되지 않는다. 

<br>

**throw 문**은 예외 상황을 미리 파악하고 에러를 발생시켜 이후 코드가 실행되지 않도록 한다. 이는 결국 에러를 발생시킨 것이므로, 프로그램 중단되는 것을 막을 수 없다. 이 에러발생에 대한 대응책이 바로 **try-catch-finally 문**이다. 

**try-catch-finally** 문을 통해 앞에서 설명한 예상치 못한 에러와 개발자가 의도한 에러 모두 대응 가능하다.
